# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
